export {default as Search} from './search/search'
export {default as SideNav} from './SideNav/SideNav.js'
export {default as TopRate} from './TopRate/TopRate'
export {default as Populer} from './Populer/Populer'
export {default as Newest} from './Newest/newest'
export {default as Loader} from './Loader/loader'
export {default as Details} from './Details/Details'